import type {
  PurchaseRequisition,
  PurchaseOrder,
  RFQ,
  GoodsReceiptItem,
  InventoryItem,
} from "@/types";

export const purchaseRequisitions: PurchaseRequisition[] = [
  {
    id: "pr-001",
    number: "PR-2025-0156",
    title: "Office Equipment & Furniture",
    grantId: "gr-001",
    grantName: "Emergency Food Security Response",
    department: "Administration",
    requestedBy: "Sarah Al-Hassan",
    requestDate: "2025-05-18",
    totalAmount: 12500,
    currency: "USD",
    status: "submitted",
    itemsCount: 8,
  },
  {
    id: "pr-002",
    number: "PR-2025-0155",
    title: "Medical Supplies - Q2 Batch",
    grantId: "gr-003",
    grantName: "Primary Health Care Support",
    department: "Health",
    requestedBy: "Dr. Omar Khalil",
    requestDate: "2025-05-17",
    totalAmount: 48200,
    currency: "USD",
    status: "approved",
    itemsCount: 15,
  },
  {
    id: "pr-003",
    number: "PR-2025-0154",
    title: "Water Pump Spare Parts",
    grantId: "gr-002",
    grantName: "Water & Sanitation Infrastructure",
    department: "WASH",
    requestedBy: "Hassan Mahmoud",
    requestDate: "2025-05-16",
    totalAmount: 8900,
    currency: "USD",
    status: "draft",
    itemsCount: 6,
  },
  {
    id: "pr-004",
    number: "PR-2025-0153",
    title: "School Learning Materials",
    grantId: "gr-004",
    grantName: "Education in Emergencies",
    department: "Education",
    requestedBy: "Layla Ahmad",
    requestDate: "2025-05-15",
    totalAmount: 22400,
    currency: "USD",
    status: "submitted",
    itemsCount: 12,
  },
  {
    id: "pr-005",
    number: "PR-2025-0152",
    title: "Hygiene Kits - Bulk Order",
    grantId: "gr-002",
    grantName: "Water & Sanitation Infrastructure",
    department: "WASH",
    requestedBy: "Hassan Mahmoud",
    requestDate: "2025-05-14",
    totalAmount: 35600,
    currency: "USD",
    status: "approved",
    itemsCount: 3,
  },
  {
    id: "pr-006",
    number: "PR-2025-0151",
    title: "Vehicle Maintenance Services",
    grantId: "gr-012",
    grantName: "Logistics & Supply Chain",
    department: "Logistics",
    requestedBy: "Khalid Nasser",
    requestDate: "2025-05-12",
    totalAmount: 6800,
    currency: "USD",
    status: "rejected",
    itemsCount: 4,
  },
  {
    id: "pr-007",
    number: "PR-2025-0150",
    title: "Agricultural Seeds & Tools",
    grantId: "gr-007",
    grantName: "Agriculture Recovery Program",
    department: "Livelihoods",
    requestedBy: "Fatima Yusuf",
    requestDate: "2025-05-10",
    totalAmount: 41200,
    currency: "USD",
    status: "submitted",
    itemsCount: 10,
  },
  {
    id: "pr-008",
    number: "PR-2025-0149",
    title: "IT Equipment Upgrade",
    grantId: "gr-001",
    grantName: "Emergency Food Security Response",
    department: "IT",
    requestedBy: "Ahmed Saleh",
    requestDate: "2025-05-08",
    totalAmount: 15800,
    currency: "USD",
    status: "cancelled",
    itemsCount: 5,
  },
];

export const purchaseOrders: PurchaseOrder[] = [
  {
    id: "po-001",
    number: "PO-2025-0847",
    vendor: "Al-Nour Medical Supplies",
    vendorEmail: "orders@alnour-med.com",
    vendorPhone: "+963 11 234 5678",
    grantId: "gr-003",
    grantName: "Primary Health Care Support",
    issueDate: "2025-05-15",
    deliveryDate: "2025-06-01",
    totalAmount: 48200,
    currency: "USD",
    status: "issued",
    shippingAddress: "Gaderon Central Warehouse, Damascus Industrial Zone, Building 12",
    bankDetails: "Commercial Bank of Syria | Account: 1234567890 | SWIFT: CBSYSYDA",
    terms: "Payment within 30 days of delivery. Goods must meet WHO quality standards. Late delivery penalty: 0.5% per week.",
    items: [
      { id: "i-1", description: "Surgical Gloves (Box of 100)", quantity: 200, unit: "Box", unitPrice: 45, total: 9000 },
      { id: "i-2", description: "Antibiotics - Amoxicillin 500mg", quantity: 5000, unit: "Tablet", unitPrice: 0.12, total: 600 },
      { id: "i-3", description: "Blood Pressure Monitors", quantity: 50, unit: "Unit", unitPrice: 85, total: 4250 },
      { id: "i-4", description: "First Aid Kits - Complete", quantity: 100, unit: "Kit", unitPrice: 343.5, total: 34350 },
    ],
  },
  {
    id: "po-002",
    number: "PO-2025-0846",
    vendor: "Damascus Water Tech",
    vendorEmail: "sales@damwater.tech",
    vendorPhone: "+963 11 876 5432",
    grantId: "gr-002",
    grantName: "Water & Sanitation Infrastructure",
    issueDate: "2025-05-10",
    deliveryDate: "2025-05-25",
    totalAmount: 35600,
    currency: "USD",
    status: "completed",
    shippingAddress: "WASH Project Site, Rural Damascus, Camp Sector B",
    bankDetails: "Bank of Syria | Account: 9876543210 | SWIFT: BSYSYDA",
    terms: "FOB destination. 12-month warranty on all equipment.",
    items: [
      { id: "i-5", description: "Hygiene Kit - Family Size", quantity: 500, unit: "Kit", unitPrice: 28, total: 14000 },
      { id: "i-6", description: "Water Purification Tablets", quantity: 10000, unit: "Tablet", unitPrice: 0.08, total: 800 },
      { id: "i-7", description: "Portable Handwashing Station", quantity: 50, unit: "Unit", unitPrice: 416, total: 20800 },
    ],
  },
];

export const rfqs: RFQ[] = [
  {
    id: "rfq-001",
    number: "RFQ-2025-0042",
    title: "Medical Supplies - Q2 Procurement",
    grantName: "Primary Health Care Support",
    deadline: "2025-05-25",
    status: "evaluating",
    vendors: [
      {
        id: "v-1",
        name: "Al-Nour Medical Supplies",
        price: 48200,
        deliveryDays: 14,
        warranty: "12 months",
        technicalScore: 92,
        committeeScore: 88,
        totalScore: 90,
        isWinner: true,
        documents: ["Technical Proposal", "Financial Offer", "Company Registration"],
      },
      {
        id: "v-2",
        name: "MedTech International",
        price: 52100,
        deliveryDays: 21,
        warranty: "18 months",
        technicalScore: 88,
        committeeScore: 82,
        totalScore: 85,
        documents: ["Technical Proposal", "Financial Offer", "ISO Certificate"],
      },
      {
        id: "v-3",
        name: "HealthFirst Trading",
        price: 45800,
        deliveryDays: 10,
        warranty: "6 months",
        technicalScore: 75,
        committeeScore: 70,
        totalScore: 72.5,
        documents: ["Financial Offer", "Company Registration"],
      },
    ],
  },
];

export const goodsReceipts: GoodsReceiptItem[] = [
  {
    id: "grn-001",
    poNumber: "PO-2025-0846",
    itemName: "Hygiene Kit - Family Size",
    orderedQty: 500,
    deliveredQty: 500,
    acceptedQty: 495,
    rejectedQty: 5,
    damagedQty: 0,
    unit: "Kit",
    receiptDate: "2025-05-22",
    receivedBy: "Warehouse Team A",
  },
  {
    id: "grn-002",
    poNumber: "PO-2025-0846",
    itemName: "Portable Handwashing Station",
    orderedQty: 50,
    deliveredQty: 48,
    acceptedQty: 46,
    rejectedQty: 0,
    damagedQty: 2,
    unit: "Unit",
    receiptDate: "2025-05-22",
    receivedBy: "Warehouse Team A",
  },
  {
    id: "grn-003",
    poNumber: "PO-2025-0847",
    itemName: "First Aid Kits - Complete",
    orderedQty: 100,
    deliveredQty: 100,
    acceptedQty: 100,
    rejectedQty: 0,
    damagedQty: 0,
    unit: "Kit",
    receiptDate: "2025-05-20",
    receivedBy: "Warehouse Team B",
  },
];

export const inventoryItems: InventoryItem[] = [
  { id: "inv-001", sku: "MED-GLV-001", name: "Surgical Gloves", category: "Medical", quantity: 1500, unit: "Box", unitCost: 45, totalValue: 67500, location: "Central Warehouse", lastUpdated: "2025-05-20" },
  { id: "inv-002", sku: "WASH-HK-001", name: "Hygiene Kit - Family", category: "WASH", quantity: 320, unit: "Kit", unitCost: 28, totalValue: 8960, location: "Central Warehouse", lastUpdated: "2025-05-22" },
  { id: "inv-003", sku: "WASH-HWS-001", name: "Handwashing Station", category: "WASH", quantity: 12, unit: "Unit", unitCost: 416, totalValue: 4992, location: "Field Store", lastUpdated: "2025-05-22" },
  { id: "inv-004", sku: "EDU-LM-001", name: "Learning Materials Set", category: "Education", quantity: 450, unit: "Set", unitCost: 15, totalValue: 6750, location: "Education Hub", lastUpdated: "2025-05-15" },
  { id: "inv-005", sku: "SNFI-TENT-001", name: "Emergency Tent 24m²", category: "Shelter", quantity: 85, unit: "Unit", unitCost: 320, totalValue: 27200, location: "Logistics Yard", lastUpdated: "2025-05-10" },
];

export function getPOById(id: string) {
  return purchaseOrders.find((po) => po.id === id);
}

export function getRFQById(id: string) {
  return rfqs.find((rfq) => rfq.id === id);
}
