import type { ProjectActivity } from "@/types";

export const projectActivities: ProjectActivity[] = [
  {
    id: "pa-001",
    title: "Food Distribution - Zone A",
    grantId: "gr-001",
    grantName: "Emergency Food Security Response",
    status: "in_progress",
    milestone: "Phase 2 Distribution",
    budgetAllocated: 120000,
    budgetSpent: 78000,
    progress: 65,
    responsibleStaff: "Sarah Al-Hassan",
    startDate: "2025-03-01",
    endDate: "2025-08-31",
  },
  {
    id: "pa-002",
    title: "Water Point Rehabilitation",
    grantId: "gr-002",
    grantName: "Water & Sanitation Infrastructure",
    status: "in_progress",
    milestone: "Site Assessment Complete",
    budgetAllocated: 85000,
    budgetSpent: 42000,
    progress: 49,
    responsibleStaff: "Hassan Mahmoud",
    startDate: "2025-02-15",
    endDate: "2025-09-30",
  },
  {
    id: "pa-003",
    title: "Mobile Clinic Operations",
    grantId: "gr-003",
    grantName: "Primary Health Care Support",
    status: "review",
    milestone: "Q2 Report Submission",
    budgetAllocated: 95000,
    budgetSpent: 88000,
    progress: 92,
    responsibleStaff: "Dr. Omar Khalil",
    startDate: "2024-06-01",
    endDate: "2025-05-31",
  },
  {
    id: "pa-004",
    title: "Temporary Learning Spaces Setup",
    grantId: "gr-004",
    grantName: "Education in Emergencies",
    status: "planning",
    milestone: "Site Selection",
    budgetAllocated: 45000,
    budgetSpent: 8000,
    progress: 18,
    responsibleStaff: "Layla Ahmad",
    startDate: "2025-03-01",
    endDate: "2025-11-30",
  },
  {
    id: "pa-005",
    title: "Shelter Kit Distribution",
    grantId: "gr-005",
    grantName: "Shelter & NFI Distribution",
    status: "completed",
    milestone: "Final Distribution",
    budgetAllocated: 65000,
    budgetSpent: 64000,
    progress: 100,
    responsibleStaff: "Khalid Nasser",
    startDate: "2025-01-15",
    endDate: "2025-04-30",
  },
  {
    id: "pa-006",
    title: "Legal Aid Consultations",
    grantId: "gr-006",
    grantName: "Protection & Legal Aid",
    status: "in_progress",
    milestone: "Case Management System",
    budgetAllocated: 55000,
    budgetSpent: 48000,
    progress: 87,
    responsibleStaff: "Nadia Farouk",
    startDate: "2024-09-01",
    endDate: "2025-08-31",
  },
  {
    id: "pa-007",
    title: "Seed Distribution Campaign",
    grantId: "gr-007",
    grantName: "Agriculture Recovery Program",
    status: "planning",
    milestone: "Farmer Registration",
    budgetAllocated: 72000,
    budgetSpent: 5000,
    progress: 7,
    responsibleStaff: "Fatima Yusuf",
    startDate: "2025-04-01",
    endDate: "2025-10-31",
  },
  {
    id: "pa-008",
    title: "Community Training Workshops",
    grantId: "gr-008",
    grantName: "Community Resilience Building",
    status: "in_progress",
    milestone: "Workshop Series 2",
    budgetAllocated: 38000,
    budgetSpent: 22000,
    progress: 58,
    responsibleStaff: "Ahmed Saleh",
    startDate: "2025-01-01",
    endDate: "2025-12-31",
  },
];

export const kanbanColumns = [
  { id: "planning", title: "Planning", status: "planning" as const },
  { id: "in_progress", title: "In Progress", status: "in_progress" as const },
  { id: "review", title: "Review", status: "review" as const },
  { id: "completed", title: "Completed", status: "completed" as const },
];
